baseurl: '/'
permalink: pretty
title: '机器人视觉与自动化实验室'
lab: 'Vision based automation science and engineering'
description: 哈尔滨工业大学（深圳）机器人视觉与自动化实验室，指导教师姜欣。
keywords: 姜欣，机器人，哈尔滨工业大学，哈尔滨工业大学（深圳），深圳，哈工大（深圳）


google_analytics_id: ""
baidu_analytics_id: "ed33d03fa163ca0f90c97f458e4659fa"
pic_bed: "https://gitee.com/zhouyanling12/robotics-hitsz-web/raw/yanling/"
homepage:
  show_call_box: false

logo:
  #mobile: "images/logo/Logo.png"
  #desktop: "images/logo/Logo.png"
  mobile: "images/logo/logo-mobile.png"
  desktop: "images/logo/logo.png"
  chinese: "images/logo/3_主页_头部“视觉机器人自动化实验室”.png"
  english: "images/logo/4_主页_头部英文题目.png"
  headw: "images/logo/5_主页_头部白色竖条.png"
  reaBg: "images/logo/12_研究内容_左侧校徽背景.png"
  pubBg: "images/logo/13_论文与项目_左侧校徽背景.png"
  desktop_height: "72px"
  foot_height: "36px"
  chinese_height: "48px"
  #desktop_height: "36px"

footer:
  copyright_text: '粤ICP备2021094001号</a>'

seo:
  meta_og_title: "机器人视觉与自动化实验室"
  meta_og_type: "website"
  meta_og_url: "https://www.hitsz-robotic.com"
  meta_og_image: ""
  meta_og_description: "哈尔滨工业大学（深圳） 姜欣机器人实验室"
  # meta_twitter_card: "summary"
  # meta_twitter_site: "@zerostaticio"
  # meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
